server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
            routes:
              - id: task-service
                uri:
                  http://localhost:8085
                predicates:
                  - Path=/v3/api-docs/task-service, api/v1/**
                filters:
                  - RewritePath=/v3/api-docs/task-service,/v3/api-docs, api/v1/**

              - id: keycloak-admin-client-docs
                uri:
                  http://localhost:8181
                predicates:
                    - Path=/v3/api-docs/keycloak-admin-client, api/v1/**
                filters:
                    - RewritePath=/v3/api-docs/keycloak-admin-client,/v3/api-docs, api/v1/**
  springdoc:
    swagger-ui:
      path: /swagger-ui/index.html

