server:
  port: 8081
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/v3/api-docs/task-service
          filters:
            - RewritePath=/v3/api-docs/task-service,/v3/api-docs

        - id: keycloak-admin-client-docs
          uri:
            http://localhost:9092
          predicates:
              - Path=/v3/api-docs/keycloak-admin-client, api/v1/**
          filters:
              - RewritePath=/v3/api-docs/keycloak-admin-client,/v3/api-docs, api/v1/**
  springdoc:
    swagger-ui:
      path: /swagger-ui/index.html

