server:
  port: 8084
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: database09
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm-2
          jwk-set-uri: http://localhost:8080/realms/realm-2/protocol/openid-connect/certs

keycloak:
  realm: realm-2
  resource: client11
  auth-server-url: http://localhost:8080/
  credentials:
    username: 'Viseth'
    password: 'Vi-222777'
    client-id: client11
    secret: 6scaeZzZ24UTDFDTPqrche49u8ud5GPP
    provider: secret
#config swagger
springdoc:
  swagger-ui:
    oauth:
      client-id: client11
      client-secret: 6scaeZzZ24UTDFDTPqrche49u8ud5GPP
      realm: realm-2
