spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm-2
          jwk-set-uri: http://localhost:8080/realms/realm-2/protocol/openid-connect/certs
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: database09
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    instances:
      kanyeClient:
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        slidingWindowSize: 5
        failureRateThreshold: 25
        slowCallRateThreshold: 25 
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, circuitbreakers

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8081

keycloak:
  realm: realm-2
  resource: client11
  auth-server-url: http://localhost:8080/
  credentials:
    username: 'Viseth'
    password: 'Vi-222777'
    client-id: client11
    secret: 6scaeZzZ24UTDFDTPqrche49u8ud5GPP
    provider: secret
#config swagger
springdoc:
  swagger-ui:
    oauth:
      client-id: client11
      client-secret: 6scaeZzZ24UTDFDTPqrche49u8ud5GPP
      realm: realm-2
